import { Document, Quiz } from '../types/document.types';

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: 'doc-1',
    title: 'Introduction to Cell Biology',
    subject: 'Biology',
    author: 'Prof. Kwame Mensah',
    uploadedAt: '2026-05-20T09:00:00Z',
    lastReadAt: '2026-06-03T14:30:00Z',
    progress: 42,
    readingTime: 840,
    estimatedReadingTime: 18,
    wordCount: 2400,
    pages: 8,
    category: 'lecture',
    coverColor: '#0B6E6E',
    content: `Cell biology is the study of cell structure and function, and it revolves around the concept that the cell is the fundamental unit of life. The field is closely related to genetics, biochemistry, molecular biology, immunology, and developmental biology.`,
    simplifiedContent: `Cell biology studies how cells work. It says the cell is the most basic part of life. This area connects to genetics and how our bodies defend themselves.`,
    chunks: [
      'Cell biology is the study of cell structure and function, and it revolves around the concept that the cell is the fundamental unit of life. The field is closely related to genetics, biochemistry, molecular biology, immunology, and developmental biology.',
      'Cells are the smallest units of life and are responsible for carrying out all the essential functions needed for an organism to survive. There are two main types of cells: prokaryotic cells, which do not have a membrane-bound nucleus, and eukaryotic cells, which do.',
      'The cell membrane, also called the plasma membrane, is a thin semi-permeable membrane that surrounds the cytoplasm of a cell. Its function is to protect the integrity of the interior of the cell by allowing certain substances into the cell while keeping others out.',
      'The nucleus is a membrane-bound organelle found in eukaryotic cells. It contains most of the cell\'s genetic material, organized as multiple long linear DNA molecules in complex with a large variety of proteins such as histones to form chromosomes.',
      'Mitochondria are often called the powerhouses of the cell. They generate most of the cell\'s supply of adenosine triphosphate, used as a source of chemical energy. In addition to supplying cellular energy, mitochondria are involved in other tasks including signaling, cellular differentiation, and cell death.',
    ],
    bookmarks: [],
    quizResults: [],
    flashcards: [
      { id: 'f1', front: 'What is the "fundamental unit of life"?', back: 'The Cell' },
      { id: 'f2', front: 'Difference between Prokaryotic and Eukaryotic?', back: 'Eukaryotic cells have a membrane-bound nucleus; Prokaryotic do not.' },
      { id: 'f3', front: 'Function of the Mitochondria?', back: 'They generate energy (ATP) for the cell. "Powerhouse of the cell".' },
    ],
  },
  {
    id: 'doc-2',
    title: 'Principles of Economics: Supply and Demand',
    subject: 'Economics',
    author: 'Dr. Abena Asante',
    uploadedAt: '2026-05-25T11:00:00Z',
    lastReadAt: '2026-06-01T10:00:00Z',
    progress: 75,
    readingTime: 1200,
    estimatedReadingTime: 14,
    wordCount: 1800,
    pages: 6,
    category: 'lecture',
    coverColor: '#7C3AED',
    content: `Supply and demand is one of the most fundamental concepts of economics. It refers to the relationship between the availability of a product (supply) and the desire for that product (demand).`,
    simplifiedContent: `Supply and demand are key ideas in economics. Supply is how much of something is available. Demand is how much people want it.`,
    chunks: [
      'Supply and demand is one of the most fundamental concepts of economics. It refers to the relationship between the availability of a product (supply) and the desire for that product (demand).',
      'Demand refers to how much (quantity) of a product or service is desired by buyers at various prices. The Law of Demand states that as prices increase, the quantity demanded decreases.',
    ],
    bookmarks: [],
    quizResults: [],
    flashcards: [
      { id: 'f4', front: 'What is the Law of Demand?', back: 'As prices increase, the quantity demanded decreases.' },
      { id: 'f5', front: 'What is Market Equilibrium?', back: 'When the quantity demanded equals the quantity supplied at a particular price.' },
    ],
  },
  {
    id: 'doc-3',
    title: 'The Future of Artificial Intelligence in Africa',
    subject: 'Technology',
    author: 'Kofi Boateng',
    uploadedAt: '2026-06-01T08:00:00Z',
    progress: 0,
    readingTime: 0,
    estimatedReadingTime: 10,
    wordCount: 1300,
    pages: 4,
    category: 'article',
    coverColor: '#059669',
    content: `Artificial Intelligence is rapidly transforming industries across the globe. In Africa, AI is being leveraged to solve local challenges in healthcare, agriculture, and finance.`,
    simplifiedContent: `AI (Artificial Intelligence) is changing many industries in Africa. It helps with local problems in health, farming, and money.`,
    chunks: ['Artificial Intelligence is transforming industries...'],
    bookmarks: [],
    quizResults: [],
    flashcards: [
      { id: 'f6', front: 'One area AI helps in African Healthcare?', back: 'Detecting malaria and tuberculosis from medical images.' },
    ],
  },
];

export const MOCK_QUIZZES: Quiz[] = [
  {
    id: 'quiz-doc1-1',
    afterChunkIndex: 3,
    questions: [
      {
        id: 'q1',
        question: 'What is the main function of the cell membrane?',
        options: [
          'To produce energy for the cell',
          'To control what enters and exits the cell',
          'To store genetic material',
          'To synthesize proteins',
        ],
        correctIndex: 1,
        explanation:
          'The cell membrane controls what substances enter and exit the cell, maintaining the cell\'s internal environment.',
      },
    ],
  },
];
